import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_absolute_error, mean_squared_error

def engineer_features(creatives_df, stats_df):
    # 1. Define efficiency rates (Targets)
    # Adding a small epsilon (1e-5) to avoid division by zero
    eps = 1e-5
    stats_df['CTR'] = stats_df['clicks'] / (stats_df['impressions'] + eps)
    stats_df['CVR'] = stats_df['conversions'] / (stats_df['clicks'] + eps)
    stats_df['VTR'] = stats_df['video_completions'] / (stats_df['impressions'] + eps)
    stats_df['viewability_rate'] = stats_df['viewable_impressions'] / (stats_df['impressions'] + eps)
    
    # 2. Sort data strictly for time-series operations
    stats_df = stats_df.sort_values(by=['creative_id', 'country', 'os', 'days_since_launch']).reset_index(drop=True)
    
    # 3. Create Autoregressive Features (Grouped by entity)
    # We group by creative, country, and OS so lags don't bleed across different ads or segments
    group_cols = ['creative_id', 'country', 'os']
    
    targets = ['CTR', 'CVR', 'VTR', 'viewability_rate', 'spend_usd']
    for col in targets:
        # Lags (1 and 2 days) - These were fine!
        stats_df[f'{col}_lag_1'] = stats_df.groupby(group_cols)[col].shift(1)
        stats_df[f'{col}_lag_2'] = stats_df.groupby(group_cols)[col].shift(2)
        
        # THE FIX: Chain .shift(1) before .rolling()
        stats_df[f'{col}_rolling_mean_3d'] = stats_df.groupby(group_cols)[col].transform(
            lambda x: x.shift(1).rolling(window=3, min_periods=1).mean()
        )
        stats_df[f'{col}_rolling_std_3d'] = stats_df.groupby(group_cols)[col].transform(
            lambda x: x.shift(1).rolling(window=3, min_periods=1).std()
        )
    # Fill NaN values generated by shifting (for the first few days of a campaign)
    # stats_df.fillna(0, inplace=True) TODO
    stats_df['is_cold_start'] = (stats_df['days_since_launch'] <= 3).astype(int)
    
    # 4. Merge with creatives data
    df = pd.merge(stats_df, creatives_df, on='creative_id', how='left')
    
    # 5. Drop forbidden and redundant columns
    cols_to_drop = [
        'advertiser_name', 'app_name', 'campaign_id_x', 'campaign_id_y', 
        'date', 'asset_file', 'impressions_last_7d', 'creative_launch_date',
        # Drop current day absolute metrics to prevent data leakage
        'impressions', 'viewable_impressions', 'clicks', 'conversions', 
        'revenue_usd', 'video_completions', 'spend_usd', 'cta_text', 
        'headline', 'subhead' # ep cta_text, headline, subhead els he tret!
    ]
    
    df = df.drop(columns=[col for col in cols_to_drop if col in df.columns], errors='ignore')
    
    # 6. Convert categoricals for LightGBM
    categorical_cols = [
        'country', 'os', 'vertical', 'format', 'language', 'theme', 
        'hook_type', 'dominant_color', 'emotional_tone'# , 'cta_text', 
        # 'headline', 'subhead'
    ]
    
    for col in categorical_cols:
        if col in df.columns:
            df[col] = df[col].astype('category')
            
    return df

# Apply the function to your data
# final_df = engineer_features(creatives_df, stats_df)

def train_lgbm_model(df, target_col='CTR'):
    print(f"--- Training Model for Target: {target_col} ---")
    
    # Define features (X) and target (y)
    # We drop all target variables from the feature set so it only learns from lags
    all_targets = ['CTR', 'CVR', 'VTR', 'viewability_rate']
    features = [col for col in df.columns if col not in all_targets and col != 'creative_id']
    
    X = df[features]
    y = df[target_col]
    groups = df['creative_id'] # Used to prevent data leakage across splits
    
    # GroupKFold configuration
    gkf = GroupKFold(n_splits=5)
    
    oof_predictions = np.zeros(len(df))
    models = []
    
    for fold, (train_idx, val_idx) in enumerate(gkf.split(X, y, groups)):
        print(f"Fold {fold + 1}")
        
        X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
        X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]
        
        # Create LightGBM datasets
        train_data = lgb.Dataset(X_train, label=y_train)
        val_data = lgb.Dataset(X_val, label=y_val, reference=train_data)
        
        # LightGBM Parameters (These are good starting defaults for tabular regressors)
        params = {
            'objective': 'regression',
            'metric': 'rmse',
            'boosting_type': 'gbdt',
            'learning_rate': 0.05,
            'num_leaves': 31,
            'feature_fraction': 0.8,
            'verbose': -1,
            'random_state': 42
        }
        
        # Train model with early stopping
        model = lgb.train(
            params,
            train_data,
            num_boost_round=1000,
            valid_sets=[train_data, val_data],
            callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]
        )
        
        # Store predictions and model
        oof_predictions[val_idx] = model.predict(X_val, num_iteration=model.best_iteration)
        models.append(model)
        
        fold_rmse = np.sqrt(mean_squared_error(y_val, oof_predictions[val_idx]))
        print(f"Fold {fold + 1} RMSE: {fold_rmse:.5f}")
        
    # Overall Validation Metrics
    overall_rmse = np.sqrt(mean_squared_error(y, oof_predictions))
    overall_mae = mean_absolute_error(y, oof_predictions)
    print(f"\nOverall Out-of-Fold RMSE: {overall_rmse:.5f}")
    print(f"Overall Out-of-Fold MAE: {overall_mae:.5f}\n")
    
    return models, features

# Example execution to train the CTR predictor:
# ctr_models, model_features = train_lgbm_model(final_df, target_col='CTR')